rootProject.name = "http4k-examples"

// http4k-connect examples
include("connect:connect-pattern")
include("connect:custom-api-client-and-fake")
include("connect:extending-connect-api-clients")
include("connect:fakes-in-official-aws-sdk")
include("connect:using-connect-api-clients")

// http4k-core examples
include("core:aws-lambda-custom-runtime")
include("core:aws-lambda-events")
include("core:aws-lambda-http")
include("core:aws-lambda-url")
include("core:bearer-auth")
include("core:datastar")
include("core:graalvm")
include("core:graphql")
include("core:hello-world")
include("core:hexagonal")
include("core:hexagonal-arrow")
include("core:hotwire")
include("core:http4k-connect")
include("core:json-api")
include("core:migration-ktor")
include("core:migration-micronaut")
include("core:migration-spring")
include("core:oauth")
include("core:openapi")
include("core:quarkus")
include("core:react-app")
include("core:typesafe-configuration")
include("core:web-content")
include("core:websockets")

// Configure project paths
project(":connect:connect-pattern").projectDir = file("http4k-connect/connect-pattern")
project(":connect:custom-api-client-and-fake").projectDir = file("http4k-connect/custom-api-client-and-fake")
project(":connect:extending-connect-api-clients").projectDir = file("http4k-connect/extending-connect-api-clients")
project(":connect:fakes-in-official-aws-sdk").projectDir = file("http4k-connect/fakes-in-official-aws-sdk")
project(":connect:using-connect-api-clients").projectDir = file("http4k-connect/using-connect-api-clients")

project(":core:aws-lambda-custom-runtime").projectDir = file("http4k-core/aws-lambda-custom-runtime")
project(":core:aws-lambda-events").projectDir = file("http4k-core/aws-lambda-events")
project(":core:aws-lambda-http").projectDir = file("http4k-core/aws-lambda-http")
project(":core:aws-lambda-url").projectDir = file("http4k-core/aws-lambda-url")
project(":core:bearer-auth").projectDir = file("http4k-core/bearer-auth")
project(":core:datastar").projectDir = file("http4k-core/datastar")
project(":core:graalvm").projectDir = file("http4k-core/graalvm")
project(":core:graphql").projectDir = file("http4k-core/graphql")
project(":core:hello-world").projectDir = file("http4k-core/hello-world")
project(":core:hexagonal").projectDir = file("http4k-core/hexagonal")
project(":core:hexagonal-arrow").projectDir = file("http4k-core/hexagonal-arrow")
project(":core:hotwire").projectDir = file("http4k-core/hotwire")
project(":core:http4k-connect").projectDir = file("http4k-core/http4k-connect")
project(":core:json-api").projectDir = file("http4k-core/json-api")
project(":core:migration-ktor").projectDir = file("http4k-core/migration-ktor")
project(":core:migration-micronaut").projectDir = file("http4k-core/migration-micronaut")
project(":core:migration-spring").projectDir = file("http4k-core/migration-spring")
project(":core:oauth").projectDir = file("http4k-core/oauth")
project(":core:openapi").projectDir = file("http4k-core/openapi")
project(":core:quarkus").projectDir = file("http4k-core/quarkus")
project(":core:react-app").projectDir = file("http4k-core/react-app")
project(":core:typesafe-configuration").projectDir = file("http4k-core/typesafe-configuration")
project(":core:web-content").projectDir = file("http4k-core/web-content")
project(":core:websockets").projectDir = file("http4k-core/websockets")