name: Handle PR for http4k upgrade
'on':
  pull_request:
    types:
    - labeled
jobs:
  handle-pr-for-http4k-upgrade:
    runs-on: ubuntu-latest
    steps:
    - name: Automatically Merge
      uses: plm9606/automerge_actions@1.2.2
      with:
        label-name: automerge
        reviewers-number: '0'
        merge-method: squash
        auto-delete: 'true'
        github-token: ${{ secrets.ORG_PUBLIC_REPO_RELEASE_TRIGGERING }}